### ISSUE TITLE
Add support of Virus total 

### ISSUE THREAD

**Issue by benochen** [righettod/website-passive-reconnaissance#2]
Hi 

From Virus total it is possible create an account and get an API key to request public endpoint. There are two endpoints interresting to add in the passive reconnaissance : 
 

- /domain/report 
- /ip-address/report 

These endpoints return existing report for domain and IP specifiy in parameter 

**References** 

- https://developers.virustotal.com/reference#domain-report
- https://developers.virustotal.com/reference#ip-address-report

**Comment by righettod** [comment]
Thanks a lot for the issue. It's interesting, however, the goal of the script is to do a passive recon in order to gather info that will be usefull for the offensive part (after the active recon).

For me, (perhaps i'm wrong 😃), the infos from VirusTotal will only give us infos on if the domain/ip was used to delivery malicious content...

What do you think?

**Comment by benochen** [comment]
Yes indeed . I close the issue it is not useful for the purpose of the script :)

**Comment by benochen** [comment]
After disscussion I re-open the issue and I take it
